### ISSUE TITLE
No Dancing GIFS???!!!!?!!

### ISSUE THREAD

**Issue by jyaconelli** [tjlagrow/CIS-422-Group-Project-1#8]
There is no gif of any dancing person while results load??!! Not sure if just on my system, or issue on all systems??
Examples of gifs I would expect:
[https://68.media.tumblr.com/2dfc3369827df9b981e111d7fd8fc732/tumblr_mvemcyarmn1rslphyo1_400.gif](url)
[http://gifdanceparty.giphy.com/assets/dancers/pumpgirl.gif](url)
[http://rs707.pbsrc.com/albums/ww74/onesuleman/miscellaneous_121.gif~c200](url)

**Comment by Vino4** [comment]
Fixed.
